In [11]:
# DUBIN Baptiste

from sklearn import datasets
import numpy as np

iris = datasets.load_iris()

In [71]:
# Code prof
Ciris = np.c_[iris.data.reshape(len(iris.data), -1), iris.target.reshape(len(iris.target), -1)]
np.random.seed(0)
np.random.shuffle(Ciris)
shuffledIrisData = Ciris[ :, :iris.data.size//len(iris.data)].reshape(iris.data.shape)
shuffledIrisTarget = Ciris[ :, iris.data.size//len(iris.data) :].reshape(iris.target.shape)

#print(shuffledIrisData)
#print("#############################################")
#print(shuffledIrisTarget)

# Apprentissage
appIrisData = shuffledIrisData[0:100]
appIrisTarget = shuffledIrisTarget[0:100]

# Dev
devIrisData = shuffledIrisData[100:130]
devIrisTarget = shuffledIrisTarget[100:130]

# Test
testIrisData = shuffledIrisData[130:150]
testIrisTarget = shuffledIrisTarget[130:150]

#print(testIrisData)
#print("#############################################")
#print(testIrisTarget)

[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 1.5]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]
 [6.  2.9 4.5 1.5]
 [5.5 2.6 4.4 1.2]
 [4.8 3.  1.4 0.3]
 [5.4 3.9 1.3 0.4]
 [5.6 2.8 4.9 2. ]
 [5.6 3.  4.5 1.5]
 [4.8 3.4 1.9 0.2]
 [4.4 2.9 1.4 0.2]
 [6.2 2.8 4.8 1.8]
 [4.6 3.6 1.  0.2]
 [5.1 3.8 1.9 0.4]
 [6.2 2.9 4.3 1.3]
 [5.  2.3 3.3 1. ]
 [5.  3.4 1.6 0.4]
 [6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]
 [5.2 2.7 3.9 1.4]
 [5.7 3.8 1.7 0.3]
 [6.  2.7 5.1 1.6]
 [5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.2 5.  1.5]
 [6.7 2.5 5.8 1.8]
 [5.6 2.5 3.9 1.1]
 [7.7 3.  6.1 2.3]
 [6.3 3.3 4.

In [83]:
print("Phase d'apprentissage\n#################################################################################")

# Proba a priori
print(f"proba de 0 = {(np.count_nonzero(appIrisTarget == 0))/appIrisTarget.size}")
print(f"proba de 1 = {(np.count_nonzero(appIrisTarget == 1))/appIrisTarget.size}")
print(f"proba de 2 = {(np.count_nonzero(appIrisTarget == 2))/appIrisTarget.size}")

print("#################################################################################")

# Moyenne
moy = np.ndarray((3,4))
for i in range (3):
    for j in range (4):
        moy[i][j] = appIrisData[appIrisTarget==i][:,j].mean()
print(f"Moyennne : \n {moy}")

print("#################################################################################")
var = np.ndarray((4,4))
for i in range (4):
    for j in range (4):
        var[i][j] = np.sqrt(appIrisData[appIrisTarget==i][:,j].var(axis=0, ddof = 1))
print(f"Variance : \n {var}")

print("#################################################################################")

def f(v, m, e):
    return ((1
                / e * np.sqrt(2 * np.pi))
                    * (np.exp((-1/2) * np.power((v - m)/ e, 2))))



print("#################################################################################")
poster = np.ones(3)

for i in range (3):
    for j in range (4):
        poster[i] *= vr[i][j]

print(f"A posteriori : \n {poster}")

print("#################################################################################")

Phase d'apprentissage
#################################################################################
proba de 0 = 0.31
proba de 1 = 0.33
proba de 2 = 0.36
#################################################################################
Moyennne : 
 [[4.96129032 3.42903226 1.46451613 0.2483871 ]
 [5.91212121 2.78484848 4.27272727 1.33939394]
 [6.45555556 2.92777778 5.41944444 1.98888889]]
#################################################################################
Variance : 
 [[0.36849009 0.4100354  0.19243767 0.10605334]
 [0.52246864 0.33083343 0.47583658 0.18189866]
 [0.55623451 0.29627315 0.43544358 0.28762851]
 [       nan        nan        nan        nan]]
#################################################################################
#################################################################################
A posteriori : 
 [3.15385938e-247 0.00000000e+000 2.03721574e+002]
#################################################################################


<ipython-input-83-199353758ef0>:21: RuntimeWarning: Degrees of freedom <= 0 for slice
  var[i][j] = np.sqrt(appIrisData[appIrisTarget==i][:,j].var(axis=0, ddof = 1))
/Users/b/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_methods.py:221: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
/Users/b/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_methods.py:253: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [ ]:
print("Phase de développement")

