In [95]:
# DUBIN Baptiste

from sklearn import datasets
import numpy as np

iris = datasets.load_iris()

In [96]:
# Code prof
Ciris = np.c_[iris.data.reshape(len(iris.data), -1), iris.target.reshape(len(iris.target), -1)]
np.random.seed(0)
np.random.shuffle(Ciris)
shuffledIrisData = Ciris[ :, :iris.data.size//len(iris.data)].reshape(iris.data.shape)
shuffledIrisTarget = Ciris[ :, iris.data.size//len(iris.data) :].reshape(iris.target.shape)

#print(shuffledIrisData)
#print("#############################################")
#print(shuffledIrisTarget)

# Apprentissage
appIrisData = shuffledIrisData[0:100]
appIrisTarget = shuffledIrisTarget[0:100]

# Dev
devIrisData = shuffledIrisData[100:130]
devIrisTarget = shuffledIrisTarget[100:130]

# Test
testIrisData = shuffledIrisData[130:150]
testIrisTarget = shuffledIrisTarget[130:150]

#print(testIrisData)
#print("#############################################")
#print(testIrisTarget)

In [112]:
print("Phase d'apprentissage\n#################################################################################")

# Proba a priori
print(f"proba de 0 = {(np.count_nonzero(appIrisTarget == 0))/appIrisTarget.size}")
print(f"proba de 1 = {(np.count_nonzero(appIrisTarget == 1))/appIrisTarget.size}")
print(f"proba de 2 = {(np.count_nonzero(appIrisTarget == 2))/appIrisTarget.size}")

print("#################################################################################")

# Moyenne
moy = np.ndarray((3,4))
for i in range (3):
    for j in range (4):
        moy[i][j] = appIrisData[appIrisTarget==i][:,j].mean()
print(f"Moyennne : \n {moy}")

print("#################################################################################")
var = np.ndarray((3,4))
for i in range (3):
    for j in range (4):
        var[i][j] = np.sqrt(appIrisData[appIrisTarget==i][:,j].var(axis=0, ddof = 1))
print(f"Variance : \n {var}")

print("#################################################################################")

def f(x, sigma, mu):
    return (1/
            (sigma*(np.sqrt(2*np.pi))))\
                *np.exp( (-1/2)*((x - mu)/
                                 sigma)**2)

vr = np.ndarray((3,4))
for i in range (2):
    for j in range (3):
        for k in range (4):
                vr[j][k] = f((np.count_nonzero(appIrisTarget == i)/appIrisTarget.size), moy[j][k], var[j][k])


print(f"Vraissamblance : \n {vr}")
print("#################################################################################")
poster = np.ones(3)

for i in range (3):
    for j in range (4):
        poster[i] *= vr[i][j]

print(f"A posteriori : \n {poster}")

Phase d'apprentissage
#################################################################################
proba de 0 = 0.31
proba de 1 = 0.33
proba de 2 = 0.36
#################################################################################
Moyennne : 
 [[4.96129032 3.42903226 1.46451613 0.2483871 ]
 [5.91212121 2.78484848 4.27272727 1.33939394]
 [6.45555556 2.92777778 5.41944444 1.98888889]]
#################################################################################
Variance : 
 [[0.36849009 0.4100354  0.19243767 0.10605334]
 [0.52246864 0.33083343 0.47583658 0.18189866]
 [0.55623451 0.29627315 0.43544358 0.28762851]]
#################################################################################
Vraissamblance : 
 [[0.08040857 0.11631084 0.27120647 1.06970614]
 [0.06744296 0.14325457 0.0933151  0.29603754]
 [0.06176035 0.13625208 0.0735992  0.20053999]]
#################################################################################
A posteriori : 
 [0.00271323 0.0002669  0.0

In [98]:
print("Phase de développement")



Phase de développement
